using System.Globalization;
using System.Text;
using SmartSurvey.Application.Reports;

namespace SmartSurvey.Infrastructure.Exports;

/// <summary>Text helpers shared by the exporters (invariant culture, UTC timestamps).</summary>
internal static class ExportText
{
    /// <summary>UTF-8 with byte-order mark, so Excel detects the encoding of CSV files.</summary>
    public static readonly Encoding Utf8WithBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true);

    /// <summary>Formats a UTC timestamp, e.g. <c>2026-09-27 14:05 UTC</c>.</summary>
    public static string Timestamp(DateTime utc) => utc.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture);

    /// <summary>Footer line, e.g. <c>Generated by SmartSurvey on 2026-09-27 14:05 UTC</c>.</summary>
    public static string GeneratedBy(ReportResult report) => $"Generated by {report.ProductName} on {Timestamp(report.GeneratedAt)}";

    /// <summary>Formats a chart value (up to two decimals, invariant).</summary>
    public static string Number(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);

    /// <summary>Replaces line breaks and tabs with spaces (single-line cells for text tables).</summary>
    public static string SingleLine(string? value) =>
        string.IsNullOrEmpty(value) ? string.Empty : value.Replace("\r\n", " ").Replace('\n', ' ').Replace('\r', ' ').Replace('\t', ' ');

    /// <summary>Parses a pre-formatted numeric cell (invariant culture).</summary>
    public static bool TryParseNumber(string? value, out double number) =>
        double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out number);

    /// <summary>Bytes of a text document in UTF-8 with BOM.</summary>
    public static byte[] ToUtf8WithBom(string text)
    {
        var preamble = Utf8WithBom.GetPreamble();
        var body = Utf8WithBom.GetBytes(text);
        var bytes = new byte[preamble.Length + body.Length];
        preamble.CopyTo(bytes, 0);
        body.CopyTo(bytes, preamble.Length);
        return bytes;
    }
}

/// <summary>Turns computed widgets into tables for the tabular formats (CSV, TXT, XLSX).</summary>
internal static class WidgetTables
{
    /// <summary>
    /// Tables of a widget in print order: KPIs, the main table (or the chart data when the widget has
    /// no table), then the extra tables (e.g. "Other" answers).
    /// </summary>
    public static IEnumerable<TableData> For(WidgetResult widget)
    {
        if (widget.Stats.Count > 0)
        {
            yield return Stats(widget.Stats);
        }

        if (widget.Table is { } table)
        {
            yield return table;
        }
        else if (widget.Chart is { Labels.Count: > 0 } chart)
        {
            yield return FromChart(chart);
        }

        foreach (var extra in widget.ExtraTables)
        {
            yield return extra;
        }
    }

    /// <summary>Two-column Statistic/Value table.</summary>
    public static TableData Stats(IEnumerable<StatItem> stats) => new()
    {
        Columns = ["Statistic", "Value"],
        Rows = stats.Select(s => new List<string> { s.Label, s.Value }).ToList(),
    };

    /// <summary>Chart data as a table: one row per category, one numeric column per series.</summary>
    public static TableData FromChart(ChartData chart)
    {
        var table = new TableData
        {
            Columns = ["Category", .. chart.Series.Select(s => string.IsNullOrWhiteSpace(s.Name) ? "Value" : s.Name)],
            NumericColumns = Enumerable.Range(1, chart.Series.Count).ToList(),
        };

        for (var i = 0; i < chart.Labels.Count; i++)
        {
            var index = i;
            table.Rows.Add([chart.Labels[i], .. chart.Series.Select(s => index < s.Values.Count ? ExportText.Number(s.Values[index]) : string.Empty)]);
        }

        return table;
    }

    /// <summary>Report header lines shared by the text formats (label, value).</summary>
    public static IEnumerable<(string Label, string Value)> HeaderLines(ReportResult report)
    {
        yield return ("Report", report.ReportName);
        if (!string.IsNullOrWhiteSpace(report.Description))
        {
            yield return ("Description", report.Description);
        }

        yield return ("Survey", report.SurveyTitle);
        yield return ("Generated", ExportText.Timestamp(report.GeneratedAt));
        yield return ("Responses", report.TotalResponses.ToString(CultureInfo.InvariantCulture));
        foreach (var filter in report.FilterSummary)
        {
            yield return ("Filter", filter);
        }
    }
}
