using System.Text;
using System.Text.Json;
using ClosedXML.Excel;
using SmartSurvey.Application.Reports;
using SmartSurvey.Application.Reports.Charts;
using SmartSurvey.Domain.Enums;
using SmartSurvey.Infrastructure.Exports;

namespace SmartSurvey.UnitTests.Reports;

/// <summary>Exporters serialise a hand-built <see cref="ReportResult"/>.</summary>
public sealed class ReportExporterTests
{
    private static readonly DateTime Generated = new(2026, 9, 27, 14, 5, 0, DateTimeKind.Utc);

    [Fact]
    public async Task Csv_has_bom_header_block_widget_sections_and_branded_footer()
    {
        var csv = Text(await new CsvReportExporter().ExportAsync(Sample()));

        Assert.StartsWith("﻿Report,Quarterly review\r\n", csv);
        Assert.Contains("Survey,\"Feedback, 2026\"\r\n", csv);
        Assert.Contains("Filter,Only completed responses\r\n", csv);
        Assert.Contains("Enjoyment\r\nQuestion,Did you enjoy the product?\r\nStatistic,Value\r\nAnswered,4\r\n\r\nOption,Count,Percent\r\nYes,3,75.0%\r\n", csv);
        Assert.Contains("Total,4,100.0%\r\n", csv);
        Assert.Contains("Broken\r\nError,The question used by this widget no longer exists.\r\n", csv);
        Assert.EndsWith("Generated by Acme Surveys on 2026-09-27 14:05 UTC\r\n", csv);
    }

    [Fact]
    public async Task Csv_writes_chart_data_when_a_widget_has_no_table()
    {
        var report = Sample();
        report.Widgets[0].Table = null;

        var csv = Text(await new CsvReportExporter().ExportAsync(report));

        Assert.Contains("Category,Responses\r\nYes,3\r\nNo,1\r\n", csv);
    }

    [Theory]
    [InlineData("plain", "plain")]
    [InlineData("a,b", "\"a,b\"")]
    [InlineData("say \"hi\"", "\"say \"\"hi\"\"\"")]
    [InlineData("two\nlines", "\"two\nlines\"")]
    [InlineData("=SUM(A1:A9)", "'=SUM(A1:A9)")]
    [InlineData("+cmd", "'+cmd")]
    [InlineData("@evil", "'@evil")]
    [InlineData("-5", "-5")]
    [InlineData("-1.5e3", "-1.5e3")]
    [InlineData("", "")]
    public void Csv_fields_are_quoted_and_formulas_neutralised(string value, string expected) =>
        Assert.Equal(expected, CsvBuilder.Escape(value));

    [Fact]
    public async Task Txt_renders_aligned_ascii_tables()
    {
        var txt = Text(await new TxtReportExporter().ExportAsync(Sample()));

        Assert.StartsWith("Quarterly review\n================", txt.Replace("\r\n", "\n"));
        Assert.Contains("Responses:   4", txt);
        Assert.Contains("| Option | Count | Percent |", txt);
        Assert.Contains("| Yes    |     3 |   75.0% |", txt);
        Assert.Contains("+--------+-------+---------+", txt);
        Assert.Contains("Error: The question used by this widget no longer exists.", txt);
        Assert.Contains("Generated by Acme Surveys", txt);
    }

    [Fact]
    public void Txt_tables_shorten_long_cells_and_flatten_line_breaks()
    {
        var text = new StringBuilder();
        TextTable.Render(text, new TableData { Columns = ["Answer"], Rows = [[new string('x', 100)], ["a\r\nb"]] });

        var output = text.ToString();
        Assert.Contains(new string('x', TextTable.MaxCellWidth - 3) + "...", output);
        Assert.Contains("| a b", output);
    }

    [Fact]
    public async Task Json_wraps_the_result_in_an_envelope_with_camel_case_and_string_enums()
    {
        using var json = JsonDocument.Parse(await new JsonReportExporter().ExportAsync(Sample()));
        var root = json.RootElement;

        Assert.Equal(JsonReportExporter.FormatName, root.GetProperty("format").GetString());
        Assert.Equal(1, root.GetProperty("version").GetInt32());
        Assert.Equal("Acme Surveys", root.GetProperty("generator").GetString());
        var widget = root.GetProperty("report").GetProperty("widgets")[0];
        Assert.Equal("PieChart", widget.GetProperty("type").GetString());
        Assert.Equal("Pie", widget.GetProperty("chart").GetProperty("kind").GetString());
        Assert.Equal(4, root.GetProperty("report").GetProperty("totalResponses").GetInt32());
    }

    [Fact]
    public async Task Json_keeps_non_latin_text_readable_but_escapes_html()
    {
        var report = Sample();
        report.ReportName = "Café <b>日本</b>";

        var json = Text(await new JsonReportExporter().ExportAsync(report));

        Assert.Contains("Café", json);
        Assert.Contains("日本", json);
        Assert.DoesNotContain("<b>", json);
    }

    [Fact]
    public async Task Xlsx_has_a_summary_sheet_and_one_sheet_per_widget_with_numeric_cells()
    {
        var bytes = await new XlsxReportExporter().ExportAsync(Sample());

        using var workbook = new XLWorkbook(new MemoryStream(bytes));
        Assert.Equal(["Summary", "1. Enjoyment", "2. Broken"], workbook.Worksheets.Select(w => w.Name));
        var summary = workbook.Worksheet("Summary");
        Assert.Equal("Quarterly review", summary.Cell(1, 1).GetString());
        Assert.Contains(summary.CellsUsed(), c => c.GetString() == "2. Broken" && c.HasHyperlink);

        var sheet = workbook.Worksheet("1. Enjoyment");
        var yes = sheet.CellsUsed().First(c => c.GetString() == "Yes");
        Assert.Equal(XLDataType.Number, yes.CellRight().DataType);
        Assert.Equal(3, yes.CellRight().GetDouble());
        Assert.Equal(XLDataType.Text, yes.CellRight(2).DataType); // "75.0%" stays text
    }

    [Fact]
    public void Sheet_names_are_sanitised_shortened_and_unique()
    {
        var names = new SheetNames();

        Assert.Equal("a b c", names.Next("a/b?c"));
        Assert.Equal("Sheet", names.Next("[]"));
        Assert.Equal(new string('n', 31), names.Next(new string('n', 40)));
        Assert.Equal(new string('n', 27) + " (2)", names.Next(new string('n', 40)));
        Assert.Equal("Summary", names.Next("Summary"));
        Assert.Equal("summary (2)", names.Next("summary")); // Excel sheet names are case-insensitive
    }

    [Fact]
    public async Task Pdf_is_generated_with_charts_tables_and_errors()
    {
        var bytes = await new PdfReportExporter(new SvgChartRenderer()).ExportAsync(Sample());

        Assert.True(bytes.Length > 1000);
        Assert.Equal("%PDF", Encoding.ASCII.GetString(bytes, 0, 4));
    }

    [Fact]
    public async Task Pdf_handles_empty_reports_wide_tables_and_unusual_text()
    {
        var report = Sample();
        report.Widgets.Add(new WidgetResult
        {
            Title = "Raw data 😀 — ünïcödé",
            Type = WidgetType.RawResponses,
            Table = new TableData
            {
                Columns = Enumerable.Range(1, 14).Select(i => $"Column {i}").ToList(),
                Rows = [Enumerable.Range(1, 14).Select(i => new string('w', i * 5)).ToList()],
            },
        });
        report.Widgets.Add(new WidgetResult
        {
            Title = "Nothing yet",
            Type = WidgetType.BarChart,
            Chart = new ChartData { Kind = ChartKind.Bar, Labels = [], Series = [] },
        });

        var bytes = await new PdfReportExporter(new SvgChartRenderer()).ExportAsync(report);

        Assert.Equal("%PDF", Encoding.ASCII.GetString(bytes, 0, 4));
    }

    private static string Text(byte[] bytes) => Encoding.UTF8.GetString(bytes);

    /// <summary>A report with a pie widget (stats, chart, table) and a failed widget.</summary>
    private static ReportResult Sample() => new()
    {
        ReportName = "Quarterly review",
        Description = "Numbers for the board",
        SurveyTitle = "Feedback, 2026",
        GeneratedAt = Generated,
        ProductName = "Acme Surveys",
        TotalResponses = 4,
        FilterSummary = ["Only completed responses"],
        Widgets =
        [
            new WidgetResult
            {
                Title = "Enjoyment",
                QuestionText = "Did you enjoy the product?",
                Type = WidgetType.PieChart,
                ResponseCount = 4,
                Stats = [new StatItem("Answered", "4")],
                Chart = new ChartData
                {
                    Kind = ChartKind.Pie,
                    Labels = ["Yes", "No"],
                    Series = [new ChartSeries { Name = "Responses", Values = [3, 1] }],
                },
                Table = new TableData
                {
                    Columns = ["Option", "Count", "Percent"],
                    Rows = [["Yes", "3", "75.0%"], ["No", "1", "25.0%"]],
                    Footer = ["Total", "4", "100.0%"],
                    NumericColumns = [1, 2],
                },
            },
            new WidgetResult
            {
                Title = "Broken",
                Type = WidgetType.BarChart,
                Error = "The question used by this widget no longer exists.",
            },
        ],
    };
}
